apiVersion: v1
kind: Secret
metadata:
  name: nginx-ingress-tls
  namespace: {{ .Release.Namespace }}  # Use the namespace of the release
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "ssl_certs/nginx.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "ssl_certs/nginx.key" | b64enc | quote }}
